name: CI Pipeline for Discriminant Calculator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Ручной запуск через GitHub UI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8 coverage bandit

      - name: Run tests
        run: python -m unittest lab3.test_discriminant 

      - name: Run flake8 linter
        run: flake8 lab3/discriminant.py lab3/test_discriminant.py

      - name: Run coverage
        run: |
          coverage run -m unittest lab3.test_discriminant
          coverage report -m

      - name: Run Bandit security check
        run: bandit -r .

      - name: Send success notification to Telegram
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="✅ CI pipeline успешно завершён! Все тесты, линтинг, покрытие и безопасность в порядке."

      - name: Send failure notification to Telegram
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="❌ CI pipeline завершился с ошибкой! Проверьте тесты, линтинг, покрытие или безопасность."