# .github/workflows/lab4-publish.yml
name: Publish Lab4 Website

on:
  release:
    types: [published]

# Разрешения нужны для публикации на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Prepare site for deployment
        run: |
          mkdir -p ./_site/v${{ steps.get_tag.outputs.TAG }}
          cp -r lab4/. ./_site/v${{ steps.get_tag.outputs.TAG }}/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4